@startuml
class Solution42 {
    main(String[])
    'attributes
    -siteName: String
    -author: String
    -jsFolder: String
    -cssFolder: String

    -readValueFromUser()
    -display()
}

class websiteGenerator{
    'attributes
    +websiteName: String
    +author: String
    +path: String

    +makeWebsite: String
    +makeJS: String
    +makeCSS: String
    +makeHTML: String
}

Solution42 <--o websiteGenerator
@enduml