@startuml
class Solution46 {
    -list: HashMap<String, Integer>
    +main(String[])
    +display()
}

class countInstance {
    -list: HashMap<String, Integer>
    +counter()
    -sort()
}

class readFile{
    -list: HashMap<String, Integer>
    +read()
}


Solution46 *-- readFile
Solution46 *-- countInstance
@enduml