@startuml
class Solution41 {
    main(String[])

    getFirstName()
    getLastName()
    readInput()
    output()

}
Solution41 *-- readInput
Solution41 *-- output

class readInput{
    read FILE
    sortData()
}

class sortData{
    int firstNames
    int lastNames
}

readInput <|..sortData

class output{

}




@enduml