@startuml
class Solution41 {
    'attributes
    -names: List<(String[])>

    main(String[])
        display: String
        'name name = new name();
        'Solution41 sol41 = new Solution41();
        'Scanner to scan the file, pass the directory of the text file

        'name.sortNames(input, sol41.names)
        'close the scanner

        'display = name.outputNames
        'prints the display string
}

class Names{
    'behaviors
    +sortNames(Scanner input, List<String> names)
        'if input is null
            'print 'file is empty'
        'else
            'scan all the lines
            'sort the string list

    +outputNames(List<String> names)
        'StringBuilder sb = new StringBuilder();
        'try(FileWriter object){
            'append the header
            'print the header to output file

            'for loop(iterate through the names)
                'append all names
                'print the names to the output file

        'catch the exception
        'return the string builder
}

Solution41 *-- Names

@enduml